-- Course history table for student graduation progress.
-- Apply with: psql -d pnu_pathfinder -f backend/migrations/002_course_records.sql

CREATE TABLE IF NOT EXISTS course_records (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    course_number varchar(30) NOT NULL,
    course_name varchar(150) NOT NULL,
    completion_category varchar(30) NOT NULL,
    credits integer NOT NULL,
    grade varchar(5),
    semester varchar(20) NOT NULL,
    is_retake boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_records_user_course_semester UNIQUE (user_id, course_number, semester),
    CONSTRAINT ck_course_records_credits_positive CHECK (credits > 0)
);

CREATE INDEX IF NOT EXISTS ix_course_records_id ON course_records (id);
CREATE INDEX IF NOT EXISTS ix_course_records_user_id ON course_records (user_id);
CREATE INDEX IF NOT EXISTS ix_course_records_course_number ON course_records (course_number);
